bplan/urls.py
from django.urls import include
from django.urls import path
from django.urls import re_path
from django.views.generic.base import RedirectView
from rest_framework import routers

from . import views
from .api import AddressViewSet
from .api import BezirkViewSet
from .api import BPlanDataViewSet
from .api import BPlanMultipolygonViewSet
from .api import BPlanPointViewSet
from .api import BPlanViewSet
from .api import OrtsteilViewSet

router = routers.DefaultRouter()
router.register(r"addresses", AddressViewSet, basename="addresse")
router.register(r"bezirke", BezirkViewSet, basename="bezirk")
router.register(r"ortsteile", OrtsteilViewSet, basename="ortsteil")
router.register(r"bplan/points", BPlanPointViewSet, basename="bplan_points")
router.register(
    r"bplan/multipolygons", BPlanMultipolygonViewSet, basename="bplan_multipoligon"
)
router.register(r"bplan/data", BPlanDataViewSet, basename="bplan_data")
router.register(r"bplan", BPlanViewSet, basename="bplan_all")

urlpatterns = [
    path("api/", include(router.urls)),
    path(
        "berlin/",
        views.StadtView.as_view(template_name="bplan/berlin.html"),
        name="berlin",
    ),
    re_path(
        r"^berlin/(?P<slug>[a-z\-]+)/", views.BezirkDetailView.as_view(), name="bezirk"
    ),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("downloads/", views.downloads, name="downloads"),
    path("", RedirectView.as_view(pattern_name="berlin"), name="index"),
]

bplan/models.py
from django.contrib.gis.db import models
from django.utils import timezone


class Download(models.Model):
    created = models.DateTimeField(editable=False)
    errors = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        return super().save(*args, **kwargs)

    def __str__(self):
        return str(self.created)


class Bezirk(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50)
    polygon = models.PolygonField(srid=4326)

    def __str__(self):
        return self.name


class Ortsteil(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50, default="")
    bezirk = models.ForeignKey(
        Bezirk, related_name="ortsteile", on_delete=models.CASCADE
    )
    polygon = models.MultiPolygonField(srid=4326)

    def __str__(self):
        return self.name


class Address(models.Model):
    gml_id = models.CharField(max_length=50, unique=True)
    point = models.PointField(srid=4326)
    strname = models.CharField(max_length=256)
    hsnr = models.CharField(max_length=50)
    search_name = models.CharField(max_length=256)
    plz = models.CharField(max_length=50)
    spatial_name = models.CharField(max_length=50)
    bezirk = models.ForeignKey(Bezirk, on_delete=models.CASCADE)

    def __str__(self):
        return self.strname + " " + self.hsnr


class BPlan(models.Model):
    bplanID = models.CharField(max_length=50, unique=True)
    planname = models.CharField(max_length=50)
    multipolygon = models.MultiPolygonField(srid=4326)
    multipolygon_25833 = models.MultiPolygonField(srid=25833)
    point = models.PointField(blank=True, null=True, srid=4326)
    bereich = models.TextField()
    bezirk = models.ForeignKey(Bezirk, on_delete=models.CASCADE)
    bezirk_name = models.CharField(max_length=50)
    ortsteile = models.ManyToManyField(Ortsteil)
    afs_behoer = models.CharField(max_length=256)
    afs_beschl = models.DateField(blank=True, null=True)
    afs_l_aend = models.DateField(blank=True, null=True)
    festg = models.BooleanField(default=False)
    festsg_von = models.CharField(max_length=256, blank=True, null=True)
    festsg_am = models.DateField(blank=True, null=True)
    bbg_anfang = models.DateField(db_index=True, blank=True, null=True)
    bbg_ende = models.DateField(db_index=True, blank=True, null=True)
    aul_anfang = models.DateField(db_index=True, blank=True, null=True)
    aul_ende = models.DateField(db_index=True, blank=True, null=True)
    ausleg_www = models.URLField(max_length=256, blank=True, null=True)
    scan_www = models.URLField(max_length=256, blank=True, null=True)
    grund_www = models.URLField(max_length=256, blank=True, null=True)
    gml_id = models.CharField(max_length=50, blank=True, null=True)
    fsg_gvbl_n = models.CharField(max_length=50, blank=True, null=True)
    fsg_gvbl_s = models.CharField(max_length=50, blank=True, null=True)
    fsg_gvbl_d = models.DateField(blank=True, null=True)
    normkontr = models.CharField(max_length=50, blank=True, null=True)
    download = models.ForeignKey(
        Download, blank=True, null=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.planname

    class Meta:
        indexes = [
            models.Index(fields=["bbg_anfang", "bbg_ende"]),
            models.Index(fields=["aul_anfang", "aul_ende"]),
        ]
        ordering = ["id"]

bplan/forms.py
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Benutzername und/oder Passwort ist falsch.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        return user

bplan/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.management import call_command
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView

from .forms import LoginForm
from .models import Bezirk
from .models import Download


class BezirkDetailView(DetailView):
    model = Bezirk

    @method_decorator(never_cache)
    @xframe_options_exempt
    def dispatch(self, *args, **kwargs):
        return super(BezirkDetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["afs_behoer"] = self.request.GET.get("afs_behoer", "")
        context["map_baseurl"] = settings.MAP_BASEURL
        attribution = ""
        if hasattr(settings, "MAP_ATTRIBUTION"):
            attribution = settings.MAP_ATTRIBUTION
        context["map_attribution"] = attribution
        return context


class StadtView(TemplateView):
    @method_decorator(never_cache)
    @xframe_options_exempt
    def dispatch(self, *args, **kwargs):
        return super(StadtView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["afs_behoer"] = self.request.GET.get("afs_behoer", "")
        context["map_baseurl"] = settings.MAP_BASEURL
        attribution = ""
        if hasattr(settings, "MAP_ATTRIBUTION"):
            attribution = settings.MAP_ATTRIBUTION
        context["map_attribution"] = attribution
        return context


@never_cache
def login_user(request):
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.login(request)
            if user:
                login(request, user)
                if request.GET.get("next"):
                    return HttpResponseRedirect(request.GET.get("next"))
                else:
                    return HttpResponseRedirect(reverse("downloads"))
    return render(request, "login.html", {"form": form})


@never_cache
def logout_user(request):
    logout(request)
    return render(request, "logout.html")


@never_cache
@login_required
def downloads(request):
    errors = []
    if request.method == "POST":
        try:
            result = call_command("load_bplan")
        except Exception as e:
            errors.append(str(e))
            pass

    downloads = Download.objects.all().order_by("-created")[:20]

    return render(request, "downloads.html", {"downloads": downloads, "errors": errors})

bplan/templates/admin_base.html
<!-- Not updated to Bootstrap 5 due to no use -->

{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'app.css' %}">

    </head>

    <body class="{% block body_class %}{% endblock %}">

        <div class="container">
            <ul class="nav nav-pills fa-pull-right">
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                      {% if request.user.is_authenticated %}{{request.user}}{% else %}Benutzer{% endif %} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_superuser %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
        {% block content %}{% endblock %}


        {# Global javascript #}
        <script type="text/javascript" src="{% static 'app.js' %}"></script>
        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

bplan/templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'app.css' %}">

        <script type="text/javascript">
            area = "{% block area %}{% endblock %}";
            afs_behoer = "{{ afs_behoer }}";
            map_baseurl = "{{ map_baseurl }}";
            map_attribution = "{{ map_attribution }}";
        </script>
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% verbatim %}
        <div>
            <div class="container-fluid" ng-app="app">
                <div ng-controller="ViewController">

                    <div class="row">
                        <div class="no-padding col-md-12">
                            <data-shared-nav></data-shared-nav>
                        </div>
                    </div>

                    <div class="row" ng-controller="MapController">

                        <div data-ng-class="{'col-12' : !popupopen, 'col-6': popupopen}"
                             data-ng-show="currentView === 'map'" class="no-padding">
                            <div class='bplan-map' id="map"></div>
                        </div>

                        <div class="col-6 no-left-padding no-right-padding popup__container"
                             data-ng-if ="currentView === 'map' && popupopen">
                            <data-popup data-ng-if="currentItem" closepopup="closePopup" resetsearch="resetSearch" bplan="currentItem"></data-popup>
                        </div>

                    </div>

                    <div data-ng-controller="ListController" data-ng-show="currentView === 'list'">
                        <div
                            class="row"
                            data-ng-if="list.length === 0">
                            <div class="col-md-12">
                                Keine Ergebnisse
                            </div>
                        </div>
                        <div
                            class="row bplan-list"
                            data-ng-if="list.length > 0">
                            <div class="col-12">
                                <nav>
                                    <ul class="pagination">
                                        <li data-ng-class="{'disabled': currentPage==0}">
                                            <a  data-ng-if= "currentPage>0"
                                                data-ng-click="previousPage()"
                                                href=""
                                                aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                            <a  data-ng-if= "currentPage==0"
                                                href=""
                                                aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                        <li><a href="#">Seite {{ currentPage +1 }} von {{Math.ceil(list.length/pageSize)}}</a></li>
                                        <li data-ng-class="{'disabled': currentPage >= (list.length/pageSize -1)}">
                                            <a  data-ng-if="currentPage >= (list.length/pageSize -1)"
                                                href=""
                                                aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                            <a  data-ng-if="currentPage < list.length/pageSize -1"
                                                data-ng-click="nextPage()"
                                                href=""
                                                aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div data-ng-if="!isMobile" class="row">
                            <div class="no-padding col-md-12" data-ng-show="currentView === 'list'">
                                <div
                                    class="row"
                                    data-ng-if="list.length > 0"
                                    data-ng-repeat="bplan in list| startFrom:currentPage*pageSize | limitTo:pageSize">
                                    <listitem
                                        data-ng-if="$index <= (currentPage*pageSize + pageSize)"
                                        data-index="$index"
                                        data-currentbplan="places.currentBplan"
                                        data-status="bplan.properties.status"
                                        data-pk="bplan.properties.pk">
                                    </listitem>
                                </div>
                            </div>
                        </div>
                        <div data-ng-if="isMobile" class="row">
                            <div class="no-padding col-md-12" data-ng-show="currentView === 'list'">
                                <div
                                    data-ng-if="list.length > 0"
                                    data-ng-repeat="bplan in list| startFrom:currentPage*pageSize | limitTo:pageSize">
                                    <listitemmobile
                                        data-ng-if="$index <= (currentPage*pageSize + pageSize)"
                                        data-index="$index"
                                        data-currentbplan="places.currentBplan"
                                        data-status="bplan.properties.status"
                                        data-pk="bplan.properties.pk">
                                    </listitemmobile>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endverbatim %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'app.js' %}"></script>
        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}

    </body>
</html>

bplan/templates/downloads.html
<!-- Not updated to Bootstrap 5 due to no use -->

{% extends 'admin_base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

	<h2>Latest Downloads</h2>

	{% if errors %}
		{% for error in errors %}
		<div class="alert alert-danger" role="alert">{{ error }}</div>
		{% endfor %}
	{% endif %}

	{% for download in downloads %}
	<div class="panel panel-default">
		<div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
			<h4 class="panel-title">
				<a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
				  {{ download.created }}
				</a>
			</h4>
		</div>
		<div id="collapse{{ forloop.counter }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ forloop.counter }}">
			<div class="panel-body">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">Neue Bpläne</h3>
					</div>
					<div class="panel-body">
					<b>Anzahl: </b>{{ download.bplan_set.all.count}}<br>
					{% for bplan in download.bplan_set.all %}
					<a href="{% url 'admin:bplan_bplan_change' bplan.pk %}">{{ bplan.planname }}</a>
					{% endfor %}
					</div>
				</div>

				{% if download.errors %}
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">Errors</h3>
					</div>
					<div class="panel-body">
					{{ download.errors}}
					</div>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
	{% endfor %}
	{% if request.user.is_superuser %}
	<a href="{% url 'admin:bplan_download_changelist' %}">more...</a>
	{% endif %}

	</div>
	<div class="col-md-12 col-md-offset-5" style="margin-top: 30px;">
		<form action="{% url 'downloads' %}" method="post">{% csrf_token %}
			<button type="submit" id="btn" class="btn btn-default btn-lg has-spinner">
				<span class="icon-spinner"><i class="fas fa-spinner load-animate" aria-hidden="true"></i></span>
    			Download Bpläne
			</button></br>
			<small>This might take a while (1 to 2 Minutes)</small>
		</form>
	</div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'custom.js' %}"></script>
{% endblock %}

bplan/templates/login.html
<!-- Not updated to Bootstrap 5 due to no use -->
{% extends 'admin_base.html' %}

{% block content %}
<div class="container">
<h2>Anmeldung</h2>

{% if not request.user.is_authenticated %}

    <div id="login">
        <form class="form-horizontal" role="form" name="LoginForm" action="" method="post" >
            {% csrf_token %}

            {% if form.non_field_errors %}
                <div class="form-errors">
                    {% for error in form.non_field_errors %}
                    <p class="alert alert-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
            {% endif %}

            <div class="form-group">
                <label class="col-lg-2 control-label" for="username">Username</label>
                <div class="col-lg-4">
                    <input class="form-control" type="text" id="username" name="username"  placeholder="Username">
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label" for="password">Password</label>
                <div class="col-lg-4">
                    <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-3">
                    <button type="submit" value="Login" class="btn btn-primary">Anmelden</button>
                </div>
            </div>
        </form>
    </div>

{% else %}
Sie sind bereits angemeldet
{% endif %}
</div>
{% endblock %}

bplan/templates/logout.html
{% extends 'admin_base.html' %}

{% block content %}
<div class="container">
	<h2><small>Abmeldung</small></h2>
	<div id="logout">
	    <p>Sie haben sich erfolgreich abgemeldet!</p>
	    <a href="{% url 'login' %}">Wieder anmelden</a>
	</div>
</div>
{% endblock %}